[package]
name = "pinocchio-rosetta-transfer-lamports"
version = "1.0.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
pinocchio = "0.4"

[dev-dependencies]
solana-program-test = "2.0.3"
solana-sdk = "2.0.3"

[lib]
crate-type = ["cdylib", "lib"]
